language: python
python:
  - "2.6"
  - "2.7"

matrix:
  include:
    - python: "3.2"
      env: EXTRA_REQUIREMENTS=https://github.com/surfly/gevent/archive/master.zip#egg=gevent
    - python: "3.3"
      env: EXTRA_REQUIREMENTS=https://github.com/surfly/gevent/archive/master.zip#egg=gevent
    - python: "pypy"
      env: EXTRA_REQUIREMENTS="cffi https://github.com/gevent-on-pypy/pypycore/archive/master.zip https://github.com/schmir/gevent/archive/pypy-hacks.zip" GEVENT_LOOP=pypycore.loop

  allow_failures:
    - python: "pypy"
    - python: "3.3"

install:
  - sudo apt-get install libev4 cython
  - pip install $EXTRA_REQUIREMENTS -r requirements.txt
  - pip install unittest2 || true

script:
  - coverage run $(which nose2)
  - flake8 yay

after_success:
  - coveralls

notifications:
    irc: "irc.oftc.net#yaybu"
    on_success: change
    on_failure: always

