language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

# FIXME: Remove this before merging
matrix:
  allow_failures:
    - python: "3.2"
    - python: "3.3"
    - python: "pypy"

install:
  - pip install -r requirements.txt
  - pip install unittest2 || true

script:
  - coverage run $(which nose2)
  - flake8 yay

after_success:
  - coveralls

notifications:
    irc: "irc.oftc.net#yaybu"
    on_success: change
    on_failure: always

