language: python
python: []

matrix:
  include:
    - python: "2.6"
      env: GEVENT=gevent==1.0
    - python: "2.7"
      env: GEVENT=gevent==1.0
    - python: "3.2"
      env: GEVENT=git+git://github.com/surfly/gevent@master#egg=gevent
    - python: "3.3"
      env: GEVENT=git+git://github.com/surfly/gevent@master#egg=gevent
    - python: "3.4"
      env: GEVENT=git+git://github.com/surfly/gevent@master#egg=gevent
    - python: "pypy"
      env: GEVENT=git+git://github.com/surfly/gevent@master#egg=gevent

  allow_failures:
    - python: "3.4"

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pip install cython==0.20.1; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --allow-external argparse --allow-unverified argparse 'argparse>=1.2.1,<1.3'; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then pip install cffi; fi
  - CFLAGS=-Wno-error=declaration-after-statement pip install $GEVENT
  - pip install -r requirements.txt

script:
  - coverage run $(which nose2)
  - flake8 yay

after_success:
  - coveralls

notifications:
    irc: "irc.oftc.net#yaybu"
    on_success: change
    on_failure: always

