language: python
python: []

matrix:
  include:
    - python: "2.6"
      env: GEVENT=gevent==1.0
    - python: "2.7"
      env: GEVENT=gevent==1.0
    - python: "3.2"
      env: GEVENT=git+git://github.com/surfly/gevent@master#egg=gevent
    - python: "3.3"
      env: GEVENT=git+git://github.com/surfly/gevent@master#egg=gevent
    - python: "pypy"
      env: GEVENT=git+git://github.com/schmir/gevent@pypy-hacks#egg=gevent GEVENT_LOOP=pypycore.loop

  allow_failures:
    - python: "pypy"
    - python: "3.3"

install:
  - if [[ $TRAVIS_SOLO != 'yes' ]]; then pip install coveralls; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pip install cython==0.19.2; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then sudo apt-get install libev-dev; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then pip install cffi; fi
  - pip install $GEVENT
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then pip install git+git://github.com/gevent-on-pypy/pypycore@master#egg=pypycore; fi
  - pip install -r requirements.txt

script:
  - coverage run $(which nose2)
  - flake8 yay

after_success:
  - coveralls

notifications:
    irc: "irc.oftc.net#yaybu"
    on_success: change
    on_failure: always

