language: python

matrix:
  include:
    - python: "2.6"
      env: GEVENT=gevent==1.0
    - python: "2.7"
      env: GEVENT=gevent==1.0
    - python: "3.2"
      env: GEVENT=git+git://github.com/surfly/gevent@master#egg=gevent
    - python: "3.3"
      env: GEVENT=git+git://github.com/surfly/gevent@master#egg=gevent
    - python: "pypy"
      env: GEVENT="cffi git+git://github.com/schmir/gevent@pypy-hacks#egg=gevent git+git://github.com/gevent-on-pypy/pypycore@master#egg=pypycore" GEVENT_LOOP=pypycore.loop

  allow_failures:
    - python: "pypy"
    - python: "3.3"

install:
  - sudo apt-get install libev4 cython
  - pip install $GEVENT
  - pip install -r requirements.txt
  - pip install unittest2 || true

script:
  - coverage run $(which nose2)
  - flake8 yay

after_success:
  - coveralls

notifications:
    irc: "irc.oftc.net#yaybu"
    on_success: change
    on_failure: always

